name: gh-pages
on:
  push:
    branches:
    - main
    - develop

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - run: yarn
    - run: yarn build
      env:
        DOCFX__SECRETS__GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        cp -r samples/_site/* ${{ runner.temp }}/_site
        dir=${GITHUB_REF##*/}
        git fetch origin gh-pages
        git checkout gh-pages
        git rm -r --ignore-unmatch $dir
        mkdir -p $dir
        cp -r ${{ runner.temp }}/_site/* $dir
        git add $dir
        git config user.email ${{ github.event.head_commit.author.email }}
        git config user.name ${{ github.event.head_commit.author.name }}
        # Ignore empty commits
        git diff-index --quiet HEAD || (git commit -a -m "docfx: ${{ github.event.head_commit.message }}" && git push)
      name: Publish GitHub Pages
