name: gh-pages
on:
  push:
    branches:
    - main

jobs:
  gh-pages:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - run: yarn
    - run: yarn build
      env:
        DOCFX__SECRETS__GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        mkdir -p ${{ runner.temp }}/_site
        cp -r samples/_site/* ${{ runner.temp }}/_site
        git fetch origin gh-pages
        git checkout -f gh-pages
        git clean -xdff
        git rm -r --ignore-unmatch .
        cp -r ${{ runner.temp }}/_site/* .
        git add *
        git config user.email ${{ github.event.head_commit.author.email }}
        git config user.name ${{ github.event.head_commit.author.name }}

        # Ignore empty commits
        git diff-index --quiet HEAD || (git commit -a -m "docfx: ${{ github.event.head_commit.message }}" && git push)
      shell: bash
      name: Publish GitHub Pages
